import Sidebar from "@/components/Sidebar";
import "@/app/globals.css";
import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import SidebarItem from "@/components/SidebarItem";
import { HiOutlineChartSquareBar } from "react-icons/hi";

const kanit = Kanit({
  weight: "400",
  subsets: ["thai", "latin-ext"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${kanit.className} flex`}>
        <Sidebar>
          <SidebarItem
            icon={<HiOutlineChartSquareBar className="text-3xl h-full" />}
            text="หน้าหลัก"
          />
        </Sidebar>
        {children}
      </body>
    </html>
  );
}
