import "@/app/globals.css";
import type { Metadata } from "next";
import { Kanit } from "next/font/google";

const kanit = Kanit({
  weight: "400",
  subsets: ["thai", "latin-ext"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} flex relative max-w-screen max-h-screen overflow-hidden`}
      >
        <div className="hidden lg:block lg:w-[400px] lg:h-[400px] rounded-full bg-gradient-1 absolute lg:top-[150px] lg:left-[372px] blur-[100px]" />
        <div className="hidden lg:block lg:w-[200px] lg:h-[200px] rounded-full bg-gradient-1 absolute lg:bottom-[108px] lg:right-[388px] blur-[100px]" />

        <div className="md:hidden w-[200px] h-[200px] rounded-full bg-gradient-1 absolute top-[50px] left-[0px] blur-[100px]" />
        <div className="md:hidden w-[200px] h-[200px] rounded-full bg-gradient-1 absolute bottom-[20px] right-[0px] blur-[100px]" />
        <div className="z-30 flex">{children}</div>
      </body>
    </html>
  );
}
